$(COUCHBASE_CMAKE_BUILD_DIRECTORY)/CMakeCache.txt: $(COUCHBASE_CMAKE_SOURCE_DIRECTORY)/CMakeLists.txt
	$(CMAKE) \
		-S $(COUCHBASE_CMAKE_SOURCE_DIRECTORY) \
		-B $(COUCHBASE_CMAKE_BUILD_DIRECTORY) \
		-DCMAKE_BUILD_TYPE=$(if $(COUCHBASE_CMAKE_BUILD_TYPE),$(COUCHBASE_CMAKE_BUILD_TYPE),RelWithDebInfo) \
		-DCMAKE_C_COMPILER="$(CC)" \
		-DCMAKE_CXX_COMPILER="$(CXX)" \
		-DCMAKE_C_FLAGS="$(COMMON_FLAGS)" \
		-DCMAKE_CXX_FLAGS="$(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)" \
		-DCOUCHBASE_PHP_INCLUDES="$(INCLUDES)" \
		-DCOUCHBASE_PHP_LIBDIR="$(phplibdir)"

$(COUCHBASE_CMAKE_BUILD_DIRECTORY)/couchbase.$(SHLIB_DL_SUFFIX_NAME): $(COUCHBASE_CMAKE_BUILD_DIRECTORY)/CMakeCache.txt
	$(CMAKE) \
		--build $(COUCHBASE_CMAKE_BUILD_DIRECTORY) \
		--verbose

cmake-build: $(COUCHBASE_CMAKE_BUILD_DIRECTORY)/couchbase.$(SHLIB_DL_SUFFIX_NAME)

.PHONY: cmake-build
