name: test-windows
permissions: {}

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


jobs:
  build_windows_with_builder:
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build the extension
        uses: php/php-windows-builder/extension@v1
        with:
          php-version: '8.1'
          ts: 'nts'
          arch: 'x64'
          args: --disable-zts
      - name: Check
        run: |
          dir